# top level variables
COMPILER = GCC
BUILD_TYPE = DEBUG
USE_COMMON_HEADER = TRUE
PRE_COMPILE_HEADER = TRUE
INSTALL_PREFIX = /usr/local

# libraries
USE_GOOGLE_TEST = TRUE
USE_NLOHMANN_JSON = TRUE
USE_BOOST = TRUE
